version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device_api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: 'ADMIN'
      ME_CONFIG_BASICAUTH_PASSWORD: 'ADMIN'
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '8082:16686' # Jaeger UI
      - '14268'
      - '14250'

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - '1888:1888' # pprof extension
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # http gRPC receiver
      - '55679:55679' # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger
